---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
   - ntp

- name: Installation
  include_tasks: "{{ ansible_os_family|lower }}.yml"
  tags:
   - ntp

- name: Copy the chrony.conf template file
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_location }}"
    mode: "0644"
    owner: root
    group: root
  notify:
    - restart chrony
  tags:
   - ntp

- name: Start and enable chrony service
  service:
    name: "{{ chrony_service_name }}"
    state: "{{ chrony_service_state }}"
    enabled: "{{ chrony_service_enabled }}"
  tags:
   - ntp

- name: Ensure tzdata package is installed
  package:
    name: "{{ chrony_tzdata_package }}"
    state: present
  tags:
   - ntp

- name: Set timezone
  timezone:
    name: "{{ chrony_timezone }}"
  tags:
   - ntp